version: 2
jobs:
  build:
    working_directory: /opt/workspace
    docker:
      - image: jetthoughts/android-react-native:1.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run: yarn run test
      - deploy:
          name: Build and Deploy Master to Android Crashlytics
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci-integration" ]; then
              mkdir -p ~/.gradle && cp android/gradle.properties ~/.gradle/gradle.properties
              bundle install
              cd android && bundle exec fastlane android beta
            fi
