version: 2
jobs:
  build:
    working_directory: /opt/workspace
    docker:
      - image: jetthoughts/android-react-native:1.0
    steps:
      - checkout:
          post:
            - cp -r licenses/. $ANDROID_HOME/licenses
      - run:
          name: Install dependencies
          command: yarn
      - run: yarn run test
      - deploy:
          name: Build and Deploy Master to Android Crashlytics
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci-integration" ]; then
              mkdir -p ~/.gradle && cp android/gradle.properties ~/.gradle/gradle.properties
              cd android && bundle install
              touch ~/.android/repositories.cfg
              bundle exec fastlane beta
            fi
