version: 2
jobs:
  android:
    working_directory: ~/project
 
    docker:
      - image: circleci/android:api-27-node8-alpha
 
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
     - run:
          name: Install dependencies
          command: yarn
      - run: yarn run test
       - deploy:
          name: Build and Deploy Master to Android Crashlytics
          command: |
            if [ "${CIRCLE_BRANCH}" == "circleci-integration" ]; then
              mkdir -p ~/.gradle && cp android/gradle.properties ~/.gradle/gradle.properties
              cd android && bundle install
              bundle exec fastlane beta
            fi
