export default {
  login: 'Login',
  selectUser: 'Select User',
  loading: 'Loading',
  password: 'Password',
  email: 'Email',
  organization: 'Organization',
  user: 'User',
  home: 'Home',
  homeMessage: 'Welcome',
  profile: 'Profile',
  profileMessage: 'Generic message',
  logout: 'Logout',
  gatherAction: 'Gather',
  weighAction: 'Weigh',
  baleAction: 'Bale',
  changeRole: 'Change Role',
  changeUser: 'Change User',
  roleSelectionTitle: 'Select an activity:',
  gatherTitle: 'Gather',
  weighTitle: 'Weigh',
  baleTitle: 'Bale',
  month0: 'January',
  month1: 'February',
  month2: 'March',
  month3: 'April',
  month4: 'May',
  month5: 'June',
  month6: 'July',
  month7: 'August',
  month8: 'September',
  month9: 'October',
  month10: 'November',
  month11: 'December',
  day0: 'Monday',
  day1: 'Tuesday',
  day2: 'Wednesday',
  day3: 'Thursday',
  day4: 'Friday',
  day5: 'Saturday',
  day6: 'Sunday',
  startTravel: 'Start travelling',
  baleComponentBale: 'Bale',
  baleComponentType: 'Type',
  baleComponentWeight: 'Weight',
  baleButtonText: 'Edit bale',
  bale: 'Bale',
};
