export default {
  login: 'Iniciar Sesión',
  selectUser: 'Seleccionar Usuario',
  loading: 'Cargando',
  password: 'Contraseña',
  email: 'Correo',
  organization: 'Organización',
  user: 'Usuario',
  home: 'Inicio',
  homeMessage: 'Bienvenido',
  profile: 'Perfil',
  profileMessage: 'Mensaje genérico',
  logout: 'Cerrar Sesión',
  gatherAction: 'Recolectar',
  weighAction: 'Pesar',
  baleAction: 'Enfardar',
  changeRole: 'Cambiar Rol',
  changeUser: 'Cambiar Usuario',
  roleSelectionTitle: 'Seleccione una actividad:',
  gatherTitle: 'Recolectar',
  weighTitle: 'Pesar',
  baleTitle: 'Enfardar',
  month0: 'Enero',
  month1: 'Febrero',
  month2: 'Marzo',
  month3: 'Abril',
  month4: 'Mayo',
  month5: 'Junio',
  month6: 'Julio',
  month7: 'Agosto',
  month8: 'Setiembre',
  month9: 'Octubre',
  month10: 'Noviembre',
  month11: 'Diciembre',
  day0: 'Domingo',
  day1: 'Lunes',
  day2: 'Martes',
  day3: 'Miércoles',
  day4: 'Jueves',
  day5: 'Viernes',
  day6: 'Sábado',
  startTravel: 'Empezar recorrida',
  baleComponentBale: 'Fardo',
  baleComponentType: 'Tipo',
  baleComponentWeight: 'Peso',
  baleButtonText: 'Modificar fardo',
  bale: 'Fardo',
  history: 'HISTORIAL',
};
