export default {
  login: 'Iniciar Sesión',
  selectUser: 'Seleccionar Usuario',
  loading: 'Cargando',
  password: 'Contraseña',
  email: 'Correo',
  user: 'Usuario',
  home: 'Inicio',
  homeMessage: 'Bienvenido',
  profile: 'Perfil',
  profileMessage: 'Mensaje genérico',
  logout: 'Cerrar Sesión',
  gatherAction: 'Recolectar',
  weighAction: 'Pesar',
  baleAction: 'Enfardar',
  changeRole: 'Cambiar Rol',
  roleSelectionTitle: 'Seleccione una actividad:',
  gatherTitle: 'Recolectar',
  weighTitle: 'Pesar',
  baleTitle: 'Enfardar',
  baleComponentBale: 'Fardo',
  baleComponentType: 'Tipo',
  baleComponentWeight: 'Peso',
  baleButtonText: 'Modificar fardo',
  bale: 'Fardo',
};
